# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com

language: node_js
node_js:
    - "stable"
before_install:
    - npm install -g grunt-cli
